name: Mise à jour du classement CDL

on:
  schedule:
    - cron: '0 * * * *' # Toutes les heures
  workflow_dispatch: # Permet un déclenchement manuel

jobs:
  update-ranking:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Récupérer les données de l'API
      - name: Mettre à jour les données du classement CDL
        run: |
          curl -H "Authorization: Bearer TON_TOKEN_API" \
            https://api.pandascore.co/tournaments/15027/standings > cdl_classement.json

      # Étape 3 : Configurer Git
      - name: Configurer Git
        run: |
          git config --global user.name "Ton Nom"
          git config --global user.email "tonemail@example.com"

      # Étape 4 : Ajouter, commit et push les changements
      - name: Commit et push des modifications
        run: |
          git add cdl_classement.json
          git commit -m "Mise à jour automatique des données CDL"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
